---

- name: Copy index.html template
  ansible.builtin.template:
    src: "{{ index_template }}"
    dest: /var/www/html/index.html
    owner: apache
    group: apache
    mode: "0644"
  become: true

- name: Get webserver content
  ansible.builtin.uri:
    url: http://localhost
    return_content: true
  register: webserver_index

- name: Output content of index page
  ansible.builtin.debug:
    msg: "{{ webserver_index.content | split('\n') }}"
