[project]
site_name = "Computacenter QeP"
site_description = "Small demo project for automating stuff during QeP"
site_author = "Tim Gr√ºtzmacher"
site_url = "https://computacenter-com.github.io/qep-devops-automation/"
copyright = "Copyright &copy; Computacenter 2026"

repo_url = "https://github.com/computacenter-com/qep-devops-automation"
repo_name = "computacenter-com/qep-devops-automation"

extra_javascript = [
    "https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js",
    "assets/javascripts/extra/tablesort.js"
]

extra_css = [
    "assets/stylesheets/extra.css",
    "assets/stylesheets/tables.css"
]

nav = [
  {"QEP 2026<br>DevOps & Automation" = "index.md"},
  {"Teil 1:<br>Infrastructure as Code" = "part1.md"},
  {"Teil 2:<br>Arbeiten mit Git" = "part2.md"},
  {"Teil 3:<br>Code-Update" = "part3.md"}
]
# ----------------------------------------------------------------------------
# Section for configuring theme options
# ----------------------------------------------------------------------------
[project.theme]
variant = "modern"

logo = "assets/images/computacenter-logo.png"
favicon = "assets/images/computacenter-logo.png"

language = "de"

# Zensical provides a number of feature toggles that change the behavior
# of the documentation site.
features = [
    # "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.footnote.tooltips",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.prune",
    "navigation.sections",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    "toc.follow",
    "toc.integrate"
]

# ----------------------------------------------------------------------------
# The "theme" defines colors and more.
# ----------------------------------------------------------------------------
[project.theme.icon.admonition]
example = "lucide/search-code"

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
palette.primary = "red"
palette.accent = "blue"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
palette.primary = "blue"
palette.accent = "red"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

# ----------------------------------------------------------------------------
# The "extra" section contains miscellaneous settings.
# ----------------------------------------------------------------------------
[[project.extra.social]]
icon = "simple/githubactions"
link = "https://github.com/computacenter-com/qep-devops-automation/actions"
name = "CI/CD Pipelines"

# ----------------------------------------------------------------------------
# Markdown Extensions
# ----------------------------------------------------------------------------
# https://zensical.org/docs/setup/extensions/python-markdown/#abbreviations
[project.markdown_extensions.abbr]
# https://zensical.org/docs/setup/extensions/python-markdown/#admonition
[project.markdown_extensions.admonition]
# https://zensical.org/docs/setup/extensions/python-markdown/#attribute-lists
[project.markdown_extensions.attr_list]
# https://zensical.org/docs/setup/footer/#configuration
[project.markdown_extensions.footnotes]
# https://zensical.org/docs/setup/extensions/python-markdown/#markdown-in-html
[project.markdown_extensions.md_in_html]
# https://zensical.org/docs/setup/extensions/python-markdown-extensions/#caption
[project.markdown_extensions.pymdownx.blocks.caption]
# https://zensical.org/docs/setup/extensions/python-markdown-extensions/#details
[project.markdown_extensions.pymdownx.details]
# https://zensical.org/docs/setup/extensions/python-markdown-extensions/#emoji
[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"
# https://zensical.org/docs/setup/extensions/python-markdown-extensions/#highlight
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
linenums_style = "pymdownx-inline"
pygments_lang_class = true
# https://zensical.org/docs/setup/extensions/python-markdown-extensions/#inlinehilite
[project.markdown_extensions.pymdownx.inlinehilite]
# https://zensical.org/docs/setup/extensions/python-markdown-extensions/#keys
[project.markdown_extensions.pymdownx.keys]
# https://zensical.org/docs/setup/extensions/python-markdown-extensions/#snippets
[project.markdown_extensions.pymdownx.snippets]
auto_append = ["includes/abbreviations.md"]
base_path = [".", "docs/ansible/snippets", "docs/automation-platform/snippets"]
# https://zensical.org/docs/setup/extensions/python-markdown-extensions/#superfences
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]
# https://zensical.org/docs/authoring/content-tabs/#content-tabs
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
