---
driver:
  name: podman
platforms:
  - name: rhel9-instance1
    image: ghcr.io/timgrt/rhel9-molecule-test-image:main
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/usr/sbin/init"
    published_ports:
      - 8080:80/tcp
    groups:
      - molecule
ansible:
  cfg:
    defaults:
      interpreter_python: auto_silent
      remote_user: ansible
      roles_path: "${MOLECULE_PROJECT_DIRECTORY}/.."
